#!/usr/bin/env bash

# Sample usage: start execute|compile [-ix] <source file path>
if [ ! -d "classes" ]; then
	mkdir classes
	rm -rf classes/*

	javac -classpath classes -d classes -sourcepath src src/*.java
fi

java -classpath classes Pascal compile "$@"
